apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: asset-dev-509615
  artifacts:
    - image: asia-south2-docker.pkg.dev/asset-dev-509615/ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia-south2-docker.pkg.dev/asset-dev-509615/ticketing/assets
      context: assets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia-south2-docker.pkg.dev/asset-dev-509615/ticketing/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia-south2-docker.pkg.dev/asset-dev-509615/ticketing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.{js,jsx,ts,tsx,css}"
            dest: .
