apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-500306
  artifacts:
    - image: asia-south1-docker.pkg.dev/ticketing-dev-500306/ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia-south1-docker.pkg.dev/ticketing-dev-500306/ticketing/assets
      context: assets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia-south1-docker.pkg.dev/ticketing-dev-500306/ticketing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.{js,jsx,ts,tsx,css}"
            dest: .
