apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
        - name: assets
          image: asia-south1-docker.pkg.dev/ticketing-dev-500306/ticketing/assets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
            - name: MONGO_URI
              value: "mongodb://assets-mongo-serv:27017/assets"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: assets-serv
spec:
  selector:
    app: assets
  ports:
    - name: assets
      protocol: TCP
      port: 3000
      targetPort: 3000
